name: build and test
on:
  - push
  - pull_request
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        run: |
          sudo apt install libglfw3
          sudo apt install libglfw3-dev
          sudo apt install xz-utils
          sudo sh -c 'wget -c https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1842+6be5946ed.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
      - name: Compile
        run: |
          zig build
          zig build -Drelease-safe
      - name: Test
        run: |
          zig build test
