name: build and test
on:
  - push
  - pull_request
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        run: |
          sudo apt install freeglut3-dev
          sudo apt install libglew-dev
          sudo apt install libglfw3
          sudo apt install libglfw3-dev
          sudo apt install xz-utils
          sudo sh -c 'wget -c https://ziglang.org/builds/zig-linux-x86_64-0.12.0-dev.1802+56deb5b05.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
      - name: Compile
        run: |
          zig build --summary all
          zig build -Doptimize=ReleaseSafe --summary all
      - name: Test
        run: |
          zig build test --summary all
          zig build test -Doptimize=ReleaseSafe --summary all
